export const app = require("./app.png")
export const chevronLeft = require("./chevron-left.png")
export const cog = require("./cog.png")
export const heart = require("./heart.png")
export const info = require("./info.png")